In [4]:
import numpy as np

# Create a 1D array of integers from 1 to 10
array_1d = np.arange(1, 11)
print(array_1d)

# Create a 2D array with shape (3, 3) containing random integers between 1 and 20
array_2d = np.random.randint(1, 21, (3, 3))
print(array_2d)


[ 1  2  3  4  5  6  7  8  9 10]
[[15 13 13]
 [ 1 11 14]
 [ 4  3 11]]


In [5]:
# Create two arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Perform operations
addition = array_a + array_b
subtraction = array_a - array_b
multiplication = array_a * array_b
division = array_a / array_b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [6]:
# Properties of a 2D array
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)


Shape: (3, 3)
Size: 9
Data Type: int32


In [7]:
# Extract first row
first_row = array_2d[0, :]
# Extract last column
last_column = array_2d[:, -1]

print("First Row:", first_row)
print("Last Column:", last_column)


First Row: [15 13 13]
Last Column: [13 14 11]


In [8]:
# Reshape 1D array into 2D array (3, 4)
array_reshaped = np.arange(12).reshape(3, 4)
print(array_reshaped)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
# Statistical calculations
mean = np.mean(array_1d)
median = np.median(array_1d)
std_dev = np.std(array_1d)
variance = np.var(array_1d)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [10]:
# Boolean indexing
array_filtered = np.arange(1, 21)[np.arange(1, 21) % 3 != 0]
print(array_filtered)


[ 1  2  4  5  7  8 10 11 13 14 16 17 19 20]


In [11]:
# Create two matrices
matrix_a = np.random.randint(1, 11, (3, 3))
matrix_b = np.random.randint(1, 11, (3, 3))

# Matrix multiplication
matrix_multiplication = np.dot(matrix_a, matrix_b)
# Determinant of matrix_a
matrix_determinant = np.linalg.det(matrix_a)

print("Matrix Multiplication:\n", matrix_multiplication)
print("Determinant of Matrix A:", matrix_determinant)


Matrix Multiplication:
 [[104  80 102]
 [ 84 100  56]
 [ 44  36  42]]
Determinant of Matrix A: -51.999999999999986


In [12]:
# Create a 3D array
array_3d = np.random.randint(1, 101, (3, 3, 3))
print("3D Array:\n", array_3d)
print("Shape of 3D Array:", array_3d.shape)


3D Array:
 [[[  9  57  91]
  [ 39  73  36]
  [ 80  36  25]]

 [[ 15  55  52]
  [ 50 100  55]
  [100   7  97]]

 [[ 20  98  55]
  [ 95  38  45]
  [ 84  37  92]]]
Shape of 3D Array: (3, 3, 3)


In [13]:
# Access element in first row, second column, third depth
element_3d = array_3d[0, 1, 2]
print("Element at (0, 1, 2):", element_3d)

# Slice the second layer
second_layer = array_3d[:, :, 1]
print("Second Layer:\n", second_layer)


Element at (0, 1, 2): 36
Second Layer:
 [[ 57  73  36]
 [ 55 100   7]
 [ 98  38  37]]


In [14]:
# Reshape the 3D array into (9, 3)
array_reshaped_3d = array_3d.reshape(9, 3)
print("Reshaped Array:\n", array_reshaped_3d)


Reshaped Array:
 [[  9  57  91]
 [ 39  73  36]
 [ 80  36  25]
 [ 15  55  52]
 [ 50 100  55]
 [100   7  97]
 [ 20  98  55]
 [ 95  38  45]
 [ 84  37  92]]


In [17]:
# Create a second 3D array
array_3d_2 = np.random.randint(1, 51, (3, 3, 3))

# Element-wise addition and multiplication
addition_3d = array_3d + array_3d_2
multiplication_3d = array_3d * array_3d_2

print("Element-wise Addition:\n", addition_3d)
print("\n Element-wise Multiplication:\n", multiplication_3d)


Element-wise Addition:
 [[[ 11  58  92]
  [ 50  97  57]
  [ 84  47  60]]

 [[ 24  89  57]
  [ 56 122 100]
  [128  12 146]]

 [[ 42 122  85]
  [125  48  95]
  [121  42 141]]]

 Element-wise Multiplication:
 [[[  18   57   91]
  [ 429 1752  756]
  [ 320  396  875]]

 [[ 135 1870  260]
  [ 300 2200 2475]
  [2800   35 4753]]

 [[ 440 2352 1650]
  [2850  380 2250]
  [3108  185 4508]]]
